inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - '.git/**/*'
  NewCops: enable

# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
    - "config/**/*"

Lint/MissingSuper:
  Exclude:
    - 'app/forms/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "**/migrate/**/*"

Metrics/AbcSize:
  Exclude:
    - "**/migrate/**/*"

Metrics/MethodLength:
  Severity: refactor

Metrics/AbcSize:
  Severity: refactor