default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development: &development
  <<: *default
  database: <%= ENV.fetch("DB_PREFIX", "") %>taverneer_development
  host: localhost
  username: postgres
  gssencmode: disable

test:
  <<: *development
  database: <%= ENV.fetch("DB_PREFIX", "") %>taverneer_test
  password: postgres

production:
  <<: *default
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
