name: RSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 2.7.5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default doc job cable storage ujs test db'
        bundle install --jobs 4 --retry 3
    - name: Setup DB, Run tests
      env:
        PGHOST: postgres
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        bin/rails db:create db:schema:load
        bundle exec rspec