# TODO: add cache on gems
name: RSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
    - name: Install gems
      run: |
        bundle install

    # For debug
    # - name: Setup ssh session
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
    #     limit-access-to-actor: true

    - name: Setup DB, Run tests
      env:
        PGHOST: postgres
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        bin/rails db:create
        bin/rails db:schema:load
        bundle exec rspec